# (C) 2001-2025 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


## Used for Example design on Devkit ##

# reset interface
set_location_assignment PIN_CD58 -to resetn
set_instance_assignment -name IO_STANDARD "1.0 V" -to resetn

# fabric PLL refclk
set_location_assignment PIN_N45 -to refclk4
#set_instance_assignment -name IO_STANDARD "1.2 V" -to refclk4
set_instance_assignment -name IO_STANDARD "TRUE DIFFERENTIAL SIGNALING" -to refclk4

# refclk interface
set_location_assignment PIN_DR68 -to refclk0
set_instance_assignment -name IO_STANDARD HCSL -to refclk0
set_location_assignment PIN_CU68 -to refclk1
set_instance_assignment -name IO_STANDARD HCSL -to refclk1

# CXT TX Pin assignments
set_location_assignment PIN_DH73 -to cxl_tx_n[0]
set_location_assignment PIN_DE76 -to cxl_tx_n[1]
set_location_assignment PIN_CT73 -to cxl_tx_n[2]
set_location_assignment PIN_CM76 -to cxl_tx_n[3]
set_location_assignment PIN_CC73 -to cxl_tx_n[4]
set_location_assignment PIN_BY76 -to cxl_tx_n[5]
set_location_assignment PIN_BL73 -to cxl_tx_n[6]
set_location_assignment PIN_BH76 -to cxl_tx_n[7]
set_location_assignment PIN_AW73 -to cxl_tx_n[8]
set_location_assignment PIN_AR76 -to cxl_tx_n[9]
set_location_assignment PIN_AF73 -to cxl_tx_n[10]
set_location_assignment PIN_AC76 -to cxl_tx_n[11]
set_location_assignment PIN_T73 -to cxl_tx_n[12]
set_location_assignment PIN_G73 -to cxl_tx_n[13]
set_location_assignment PIN_E69 -to cxl_tx_n[14]
set_location_assignment PIN_P69 -to cxl_tx_n[15]
set_location_assignment PIN_DL74 -to cxl_tx_p[0]
set_location_assignment PIN_DB77 -to cxl_tx_p[1]
set_location_assignment PIN_CW74 -to cxl_tx_p[2]
set_location_assignment PIN_CJ77 -to cxl_tx_p[3]
set_location_assignment PIN_CF74 -to cxl_tx_p[4]
set_location_assignment PIN_BU77 -to cxl_tx_p[5]
set_location_assignment PIN_BP74 -to cxl_tx_p[6]
set_location_assignment PIN_BE77 -to cxl_tx_p[7]
set_location_assignment PIN_BB74 -to cxl_tx_p[8]
set_location_assignment PIN_AM77 -to cxl_tx_p[9]
set_location_assignment PIN_AJ74 -to cxl_tx_p[10]
set_location_assignment PIN_Y77 -to cxl_tx_p[11]
set_location_assignment PIN_V74 -to cxl_tx_p[12]
set_location_assignment PIN_K74 -to cxl_tx_p[13]
set_location_assignment PIN_C71 -to cxl_tx_p[14]
set_location_assignment PIN_M71 -to cxl_tx_p[15]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_tx_n[*]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_tx_p[*]

# CXT RX Pin assignments
set_location_assignment PIN_DB83 -to cxl_rx_n[0]
set_location_assignment PIN_CT79 -to cxl_rx_n[1]
set_location_assignment PIN_CJ83 -to cxl_rx_n[2]
set_location_assignment PIN_CC79 -to cxl_rx_n[3]
set_location_assignment PIN_BU83 -to cxl_rx_n[4]
set_location_assignment PIN_BL79 -to cxl_rx_n[5]
set_location_assignment PIN_BE83 -to cxl_rx_n[6]
set_location_assignment PIN_AW79 -to cxl_rx_n[7]
set_location_assignment PIN_AM83 -to cxl_rx_n[8]
set_location_assignment PIN_AF79 -to cxl_rx_n[9]
set_location_assignment PIN_Y83 -to cxl_rx_n[10]
set_location_assignment PIN_T79 -to cxl_rx_n[11]
set_location_assignment PIN_M83 -to cxl_rx_n[12]
set_location_assignment PIN_G79 -to cxl_rx_n[13]
set_location_assignment PIN_P76 -to cxl_rx_n[14]
set_location_assignment PIN_E76 -to cxl_rx_n[15]
set_location_assignment PIN_DE82 -to cxl_rx_p[0]
set_location_assignment PIN_CW80 -to cxl_rx_p[1]
set_location_assignment PIN_CM82 -to cxl_rx_p[2]
set_location_assignment PIN_CF80 -to cxl_rx_p[3]
set_location_assignment PIN_BY82 -to cxl_rx_p[4]
set_location_assignment PIN_BP80 -to cxl_rx_p[5]
set_location_assignment PIN_BH82 -to cxl_rx_p[6]
set_location_assignment PIN_BB80 -to cxl_rx_p[7]
set_location_assignment PIN_AR82 -to cxl_rx_p[8]
set_location_assignment PIN_AJ80 -to cxl_rx_p[9]
set_location_assignment PIN_AC82 -to cxl_rx_p[10]
set_location_assignment PIN_V80 -to cxl_rx_p[11]
set_location_assignment PIN_P82 -to cxl_rx_p[12]
set_location_assignment PIN_K80 -to cxl_rx_p[13]
set_location_assignment PIN_M77 -to cxl_rx_p[14]
set_location_assignment PIN_C77 -to cxl_rx_p[15]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_rx_n[*]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_rx_p[*]

#-------DDR4 COMP CH0 PIN ASSIGNMENT--------#
set_location_assignment PIN_AG63 -to mem_refclk[0]
set_instance_assignment -name IO_STANDARD "TRUE DIFFERENTIAL SIGNALING" -to mem_refclk[0] -entity ddr4
set_location_assignment PIN_B63 -to mem_ck[0][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck[0][0]
set_location_assignment PIN_D64 -to mem_ck_n[0][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck_n[0][0]
set_location_assignment PIN_B59 -to mem_bg[0][1]
set_location_assignment PIN_AT70 -to mem_bg[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_bg[0][*]
set_location_assignment PIN_AV68 -to mem_ba[0][1]
set_location_assignment PIN_AK70 -to mem_ba[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_ba[0][*]
set_location_assignment PIN_AG68 -to mem_alert_n[0]
set_location_assignment PIN_AV63 -to mem_oct_rzqin[0]
set_location_assignment PIN_H64 -to mem_par[0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_par[0]
set_location_assignment PIN_J61 -to mem_cke[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cke[0][0]
set_location_assignment PIN_B61 -to mem_odt[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_odt[0][0]
set_location_assignment PIN_H60 -to mem_act_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_act_n[0]
set_location_assignment PIN_J59 -to mem_cs_n[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cs_n[0][0]
set_location_assignment PIN_D60 -to mem_reset_n[0]
set_location_assignment PIN_AT66 -to mem_a[0][16]
set_location_assignment PIN_AV65 -to mem_a[0][15]
set_location_assignment PIN_AK66 -to mem_a[0][14]
set_location_assignment PIN_AG65 -to mem_a[0][13]
set_location_assignment PIN_AT64 -to mem_a[0][12]
set_location_assignment PIN_W64 -to mem_a[0][11]
set_location_assignment PIN_U63 -to mem_a[0][10]
set_location_assignment PIN_L64 -to mem_a[0][9]
set_location_assignment PIN_N63 -to mem_a[0][8]
set_location_assignment PIN_W62 -to mem_a[0][7]
set_location_assignment PIN_U61 -to mem_a[0][6]
set_location_assignment PIN_L62 -to mem_a[0][5]
set_location_assignment PIN_N61 -to mem_a[0][4]
set_location_assignment PIN_W60 -to mem_a[0][3]
set_location_assignment PIN_U59 -to mem_a[0][2]
set_location_assignment PIN_L60 -to mem_a[0][1]
set_location_assignment PIN_N59 -to mem_a[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_a[0][*]
set_location_assignment PIN_AV57 -to mem_dq[0][71]
set_location_assignment PIN_BF58 -to mem_dq[0][70]
set_location_assignment PIN_AT58 -to mem_dq[0][69]
set_location_assignment PIN_BF62 -to mem_dq[0][68]
set_location_assignment PIN_BC57 -to mem_dq[0][67]
set_location_assignment PIN_AV61 -to mem_dq[0][66]
set_location_assignment PIN_AT62 -to mem_dq[0][65]
set_location_assignment PIN_BC61 -to mem_dq[0][64]
set_location_assignment PIN_AN45 -to mem_dq[0][63]
set_location_assignment PIN_AA49 -to mem_dq[0][62]
set_location_assignment PIN_AA45 -to mem_dq[0][61]
set_location_assignment PIN_AN49 -to mem_dq[0][60]
set_location_assignment PIN_AK46 -to mem_dq[0][59]
set_location_assignment PIN_AD50 -to mem_dq[0][58]
set_location_assignment PIN_AD46 -to mem_dq[0][57]
set_location_assignment PIN_AK50 -to mem_dq[0][56]
set_location_assignment PIN_AA51 -to mem_dq[0][55]
set_location_assignment PIN_AD52 -to mem_dq[0][54]
set_location_assignment PIN_AK52 -to mem_dq[0][53]
set_location_assignment PIN_AA55 -to mem_dq[0][52]
set_location_assignment PIN_AN55 -to mem_dq[0][51]
set_location_assignment PIN_AK56 -to mem_dq[0][50]
set_location_assignment PIN_AN51 -to mem_dq[0][49]
set_location_assignment PIN_AD56 -to mem_dq[0][48]
set_location_assignment PIN_BC63 -to mem_dq[0][47]
set_location_assignment PIN_BM64 -to mem_dq[0][46]
set_location_assignment PIN_AY64 -to mem_dq[0][45]
set_location_assignment PIN_BJ63 -to mem_dq[0][44]
set_location_assignment PIN_AY70 -to mem_dq[0][43]
set_location_assignment PIN_BM70 -to mem_dq[0][42]
set_location_assignment PIN_BC68 -to mem_dq[0][41]
set_location_assignment PIN_BJ68 -to mem_dq[0][40]
set_location_assignment PIN_BM58 -to mem_dq[0][39]
set_location_assignment PIN_CA61 -to mem_dq[0][38]
set_location_assignment PIN_BV62 -to mem_dq[0][37]
set_location_assignment PIN_CA57 -to mem_dq[0][36]
set_location_assignment PIN_BJ61 -to mem_dq[0][35]
set_location_assignment PIN_BV58 -to mem_dq[0][34]
set_location_assignment PIN_BM62 -to mem_dq[0][33]
set_location_assignment PIN_BJ57 -to mem_dq[0][32]
set_location_assignment PIN_BC51 -to mem_dq[0][31]
set_location_assignment PIN_BF56 -to mem_dq[0][30]
set_location_assignment PIN_AV51 -to mem_dq[0][29]
set_location_assignment PIN_BC55 -to mem_dq[0][28]
set_location_assignment PIN_AT52 -to mem_dq[0][27]
set_location_assignment PIN_BF52 -to mem_dq[0][26]
set_location_assignment PIN_AT56 -to mem_dq[0][25]
set_location_assignment PIN_AV55 -to mem_dq[0][24]
set_location_assignment PIN_BC45 -to mem_dq[0][23]
set_location_assignment PIN_BF50 -to mem_dq[0][22]
set_location_assignment PIN_AV45 -to mem_dq[0][21]
set_location_assignment PIN_BC49 -to mem_dq[0][20]
set_location_assignment PIN_BF46 -to mem_dq[0][19]
set_location_assignment PIN_AT50 -to mem_dq[0][18]
set_location_assignment PIN_AT46 -to mem_dq[0][17]
set_location_assignment PIN_AV49 -to mem_dq[0][16]
set_location_assignment PIN_AA61 -to mem_dq[0][15]
set_location_assignment PIN_AK58 -to mem_dq[0][14]
set_location_assignment PIN_AA57 -to mem_dq[0][13]
set_location_assignment PIN_AK62 -to mem_dq[0][12]
set_location_assignment PIN_AD58 -to mem_dq[0][11]
set_location_assignment PIN_AD62 -to mem_dq[0][10]
set_location_assignment PIN_AN57 -to mem_dq[0][9]
set_location_assignment PIN_AN61 -to mem_dq[0][8]
set_location_assignment PIN_U57 -to mem_dq[0][7]
set_location_assignment PIN_W58 -to mem_dq[0][6]
set_location_assignment PIN_U53 -to mem_dq[0][5]
set_location_assignment PIN_L58 -to mem_dq[0][4]
set_location_assignment PIN_N53 -to mem_dq[0][3]
set_location_assignment PIN_W54 -to mem_dq[0][2]
set_location_assignment PIN_L54 -to mem_dq[0][1]
set_location_assignment PIN_N57 -to mem_dq[0][0]
set_instance_assignment -name IO_STANDARD "1.2-V POD" -to mem_dq[0][*]
set_location_assignment PIN_AV59 -to mem_dqs[0][8]
set_location_assignment PIN_AA47 -to mem_dqs[0][7]
set_location_assignment PIN_AA53 -to mem_dqs[0][6]
set_location_assignment PIN_BC65 -to mem_dqs[0][5]
set_location_assignment PIN_BJ59 -to mem_dqs[0][4]
set_location_assignment PIN_AV53 -to mem_dqs[0][3]
set_location_assignment PIN_AV47 -to mem_dqs[0][2]
set_location_assignment PIN_AA59 -to mem_dqs[0][1]
set_location_assignment PIN_N55 -to mem_dqs[0][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs[0][*]
set_location_assignment PIN_AT60 -to mem_dqs_n[0][8]
set_location_assignment PIN_AD48 -to mem_dqs_n[0][7]
set_location_assignment PIN_AD54 -to mem_dqs_n[0][6]
set_location_assignment PIN_AY66 -to mem_dqs_n[0][5]
set_location_assignment PIN_BM60 -to mem_dqs_n[0][4]
set_location_assignment PIN_AT54 -to mem_dqs_n[0][3]
set_location_assignment PIN_AT48 -to mem_dqs_n[0][2]
set_location_assignment PIN_AD60 -to mem_dqs_n[0][1]
set_location_assignment PIN_L56 -to mem_dqs_n[0][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs_n[0][*]
set_location_assignment PIN_BC59 -to mem_dbi_n[0][8]
set_location_assignment PIN_AN47 -to mem_dbi_n[0][7]
set_location_assignment PIN_AN53 -to mem_dbi_n[0][6]
set_location_assignment PIN_BJ65 -to mem_dbi_n[0][5]
set_location_assignment PIN_CA59 -to mem_dbi_n[0][4]
set_location_assignment PIN_BC53 -to mem_dbi_n[0][3]
set_location_assignment PIN_BC47 -to mem_dbi_n[0][2]
set_location_assignment PIN_AN59 -to mem_dbi_n[0][1]
set_location_assignment PIN_U55 -to mem_dbi_n[0][0]
set_instance_assignment -name IO_STANDARD "1.2-V POD" -to mem_dbi_n[0][*]

#-------DDR4 COMP CH1 PIN ASSIGNMENT--------# 

set_location_assignment PIN_AA31 -to mem_refclk[1]
set_instance_assignment -name IO_STANDARD "TRUE DIFFERENTIAL SIGNALING" -to mem_refclk[1] -entity ddr4
set_location_assignment PIN_AV33 -to mem_ck[1][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck[1][0]
set_location_assignment PIN_AT34 -to mem_ck_n[1][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck_n[1][0]
set_location_assignment PIN_AV37 -to mem_bg[1][1]
set_location_assignment PIN_AK28 -to mem_bg[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_bg[1][*]
set_location_assignment PIN_AN27 -to mem_ba[1][1]
set_location_assignment PIN_AD28 -to mem_ba[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_ba[1][*]
set_location_assignment PIN_AA27 -to mem_alert_n[1]
set_location_assignment PIN_AN31 -to mem_oct_rzqin[1]
set_location_assignment PIN_BF34 -to mem_par[1]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_par[1]
set_location_assignment PIN_BC35 -to mem_cke[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cke[1][0]
set_location_assignment PIN_AV35 -to mem_odt[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_odt[1][0]
set_location_assignment PIN_BF38 -to mem_act_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_act_n[1]
set_location_assignment PIN_BC37 -to mem_cs_n[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cs_n[1][0]
set_location_assignment PIN_AT38 -to mem_reset_n[1]
set_location_assignment PIN_AK30 -to mem_a[1][16]
set_location_assignment PIN_AN29 -to mem_a[1][15]
set_location_assignment PIN_AD30 -to mem_a[1][14]
set_location_assignment PIN_AA29 -to mem_a[1][13]
set_location_assignment PIN_AK32 -to mem_a[1][12]
set_location_assignment PIN_W30 -to mem_a[1][11]
set_location_assignment PIN_U29 -to mem_a[1][10]
set_location_assignment PIN_L30 -to mem_a[1][9]
set_location_assignment PIN_N29 -to mem_a[1][8]
set_location_assignment PIN_W32 -to mem_a[1][7]
set_location_assignment PIN_U31 -to mem_a[1][6]
set_location_assignment PIN_L32 -to mem_a[1][5]
set_location_assignment PIN_N31 -to mem_a[1][4]
set_location_assignment PIN_W34 -to mem_a[1][3]
set_location_assignment PIN_U33 -to mem_a[1][2]
set_location_assignment PIN_L34 -to mem_a[1][1]
set_location_assignment PIN_N33 -to mem_a[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_a[1][*]
set_location_assignment PIN_BF28 -to mem_dq[1][71]
set_location_assignment PIN_BC27 -to mem_dq[1][70]
set_location_assignment PIN_AV31 -to mem_dq[1][69]
set_location_assignment PIN_BF32 -to mem_dq[1][68]
set_location_assignment PIN_BC31 -to mem_dq[1][67]
set_location_assignment PIN_AV27 -to mem_dq[1][66]
set_location_assignment PIN_AT32 -to mem_dq[1][65]
set_location_assignment PIN_AT28 -to mem_dq[1][64]
set_location_assignment PIN_AT44 -to mem_dq[1][63]
set_location_assignment PIN_AV39 -to mem_dq[1][62]
set_location_assignment PIN_BC43 -to mem_dq[1][61]
set_location_assignment PIN_BF40 -to mem_dq[1][60]
set_location_assignment PIN_AT40 -to mem_dq[1][59]
set_location_assignment PIN_BC39 -to mem_dq[1][58]
set_location_assignment PIN_AV43 -to mem_dq[1][57]
set_location_assignment PIN_BF44 -to mem_dq[1][56]
set_location_assignment PIN_H23 -to mem_dq[1][55]
set_location_assignment PIN_H28 -to mem_dq[1][54]
set_location_assignment PIN_D23 -to mem_dq[1][53]
set_location_assignment PIN_D28 -to mem_dq[1][52]
set_location_assignment PIN_B21 -to mem_dq[1][51]
set_location_assignment PIN_B27 -to mem_dq[1][50]
set_location_assignment PIN_J27 -to mem_dq[1][49]
set_location_assignment PIN_J21 -to mem_dq[1][48]
set_location_assignment PIN_W11 -to mem_dq[1][47]
set_location_assignment PIN_W4 -to mem_dq[1][46]
set_location_assignment PIN_U9 -to mem_dq[1][45]
set_location_assignment PIN_U2 -to mem_dq[1][44]
set_location_assignment PIN_L11 -to mem_dq[1][43]
set_location_assignment PIN_L4 -to mem_dq[1][42]
set_location_assignment PIN_N9 -to mem_dq[1][41]
set_location_assignment PIN_N2 -to mem_dq[1][40]
set_location_assignment PIN_AK34 -to mem_dq[1][39]
set_location_assignment PIN_AN37 -to mem_dq[1][38]
set_location_assignment PIN_AK38 -to mem_dq[1][37]
set_location_assignment PIN_AN33 -to mem_dq[1][36]
set_location_assignment PIN_AA37 -to mem_dq[1][35]
set_location_assignment PIN_AA33 -to mem_dq[1][34]
set_location_assignment PIN_AD38 -to mem_dq[1][33]
set_location_assignment PIN_AD34 -to mem_dq[1][32]
set_location_assignment PIN_AN43 -to mem_dq[1][31]
set_location_assignment PIN_AD40 -to mem_dq[1][30]
set_location_assignment PIN_AK44 -to mem_dq[1][29]
set_location_assignment PIN_AN39 -to mem_dq[1][28]
set_location_assignment PIN_AA43 -to mem_dq[1][27]
set_location_assignment PIN_AA39 -to mem_dq[1][26]
set_location_assignment PIN_AD44 -to mem_dq[1][25]
set_location_assignment PIN_AK40 -to mem_dq[1][24]
set_location_assignment PIN_L40 -to mem_dq[1][23]
set_location_assignment PIN_N39 -to mem_dq[1][22]
set_location_assignment PIN_W36 -to mem_dq[1][21]
set_location_assignment PIN_N35 -to mem_dq[1][20]
set_location_assignment PIN_U39 -to mem_dq[1][19]
set_location_assignment PIN_U35 -to mem_dq[1][18]
set_location_assignment PIN_W40 -to mem_dq[1][17]
set_location_assignment PIN_L36 -to mem_dq[1][16]
set_location_assignment PIN_H34 -to mem_dq[1][15]
set_location_assignment PIN_H30 -to mem_dq[1][14]
set_location_assignment PIN_D34 -to mem_dq[1][13]
set_location_assignment PIN_J33 -to mem_dq[1][12]
set_location_assignment PIN_D30 -to mem_dq[1][11]
set_location_assignment PIN_B29 -to mem_dq[1][10]
set_location_assignment PIN_B33 -to mem_dq[1][9]
set_location_assignment PIN_J29 -to mem_dq[1][8]
set_location_assignment PIN_J17 -to mem_dq[1][7]
set_location_assignment PIN_H7 -to mem_dq[1][6]
set_location_assignment PIN_D19 -to mem_dq[1][5]
set_location_assignment PIN_J9 -to mem_dq[1][4]
set_location_assignment PIN_H19 -to mem_dq[1][3]
set_location_assignment PIN_D11 -to mem_dq[1][2]
set_location_assignment PIN_B17 -to mem_dq[1][1]
set_location_assignment PIN_H11 -to mem_dq[1][0]
set_location_assignment PIN_AV29 -to mem_dqs[1][8]
set_location_assignment PIN_AV41 -to mem_dqs[1][7]
set_location_assignment PIN_B25 -to mem_dqs[1][6]
set_location_assignment PIN_N5 -to mem_dqs[1][5]
set_location_assignment PIN_AA35 -to mem_dqs[1][4]
set_location_assignment PIN_AA41 -to mem_dqs[1][3]
set_location_assignment PIN_N37 -to mem_dqs[1][2]
set_location_assignment PIN_B31 -to mem_dqs[1][1]
set_location_assignment PIN_B13 -to mem_dqs[1][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs[1][*]
set_location_assignment PIN_AT30 -to mem_dqs_n[1][8]
set_location_assignment PIN_AT42 -to mem_dqs_n[1][7]
set_location_assignment PIN_D26 -to mem_dqs_n[1][6]
set_location_assignment PIN_L7 -to mem_dqs_n[1][5]
set_location_assignment PIN_AD36 -to mem_dqs_n[1][4]
set_location_assignment PIN_AD42 -to mem_dqs_n[1][3]
set_location_assignment PIN_L38 -to mem_dqs_n[1][2]
set_location_assignment PIN_D32 -to mem_dqs_n[1][1]
set_location_assignment PIN_D15 -to mem_dqs_n[1][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs_n[1][*]
set_location_assignment PIN_BC29 -to mem_dbi_n[1][8]
set_location_assignment PIN_BC41 -to mem_dbi_n[1][7]
set_location_assignment PIN_J25 -to mem_dbi_n[1][6]
set_location_assignment PIN_U5 -to mem_dbi_n[1][5]
set_location_assignment PIN_AN35 -to mem_dbi_n[1][4]
set_location_assignment PIN_AN41 -to mem_dbi_n[1][3]
set_location_assignment PIN_U37 -to mem_dbi_n[1][2]
set_location_assignment PIN_J31 -to mem_dbi_n[1][1]
set_location_assignment PIN_J13 -to mem_dbi_n[1][0]
set_instance_assignment -name IO_STANDARD "1.2-V POD" -to mem_dbi_n[1][*]



